// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOzTuEHyWrCc5TYGE2OEtNkVEW76ie890',
    appId: '1:850151656546:web:067d04d4b110192d58d53b',
    messagingSenderId: '850151656546',
    projectId: 'book-club-e0c29',
    authDomain: 'book-club-e0c29.firebaseapp.com',
    storageBucket: 'book-club-e0c29.appspot.com',
    measurementId: 'G-3FK2SHKDVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeaKF9EZfwEAl4u3pZdMJstYNrsmN1l1I',
    appId: '1:850151656546:android:a158bea941c4d69458d53b',
    messagingSenderId: '850151656546',
    projectId: 'book-club-e0c29',
    storageBucket: 'book-club-e0c29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeoxyM8EWUtPg7EnoTlysOxAsiSCOW4ug',
    appId: '1:850151656546:ios:c94ad2296bfe10d258d53b',
    messagingSenderId: '850151656546',
    projectId: 'book-club-e0c29',
    storageBucket: 'book-club-e0c29.appspot.com',
    iosClientId:
        '850151656546-14gdjln8unt9i1jnv14l833pik5kpqpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeoxyM8EWUtPg7EnoTlysOxAsiSCOW4ug',
    appId: '1:850151656546:ios:c94ad2296bfe10d258d53b',
    messagingSenderId: '850151656546',
    projectId: 'book-club-e0c29',
    storageBucket: 'book-club-e0c29.appspot.com',
    iosClientId:
        '850151656546-14gdjln8unt9i1jnv14l833pik5kpqpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookClubApp',
  );
}
